root-folder: banking
modules-folder: null
vars:
  database: "FINANCE_CORE_DEV"
  warehouse: "COMPUTE_WH"
  role: "SYSADMIN"
  environment: "dev"
  raw_schema: "RAW"
  clean_schema: "CLEAN"
  conformed_schema: "CONFORMED"
  governance_schema: "GOVERNANCE"

create-change-history-table: true
change-history-table: "FINANCE_CORE_DEV.METADATA.SCHEMACHANGE_HISTORY"
autocommit: true
dry-run: false
