/* ============================================================
   schemachange Repeatable: R__masking_policies.sql
   PURPOSE : PII data masking policies for the Medallion layers
   Re-runs automatically when this file changes.
   ============================================================ */

USE DATABASE {{ database }};
USE SCHEMA GOVERNANCE;

-- Unset policies before replacing (policies cannot be replaced while attached)
-- Bronze layer
ALTER TABLE IF EXISTS BRONZE.T_CUSTOMER MODIFY COLUMN FIRST_NAME UNSET MASKING POLICY;
ALTER TABLE IF EXISTS BRONZE.T_CUSTOMER MODIFY COLUMN LAST_NAME UNSET MASKING POLICY;
ALTER TABLE IF EXISTS BRONZE.T_CUSTOMER MODIFY COLUMN EMAIL_ADDRESS UNSET MASKING POLICY;
ALTER TABLE IF EXISTS BRONZE.T_CUSTOMER MODIFY COLUMN PHONE_NUMBER UNSET MASKING POLICY;
ALTER TABLE IF EXISTS BRONZE.T_CUSTOMER MODIFY COLUMN CITY UNSET MASKING POLICY;
ALTER TABLE IF EXISTS BRONZE.T_CUSTOMER MODIFY COLUMN STATE_PROVINCE UNSET MASKING POLICY;
ALTER TABLE IF EXISTS BRONZE.T_ACCOUNT MODIFY COLUMN ACCOUNT_ID UNSET MASKING POLICY;
ALTER TABLE IF EXISTS BRONZE.T_TRANSACTION MODIFY COLUMN AMOUNT UNSET MASKING POLICY;
-- Silver layer
ALTER TABLE IF EXISTS SILVER.DIMCUSTOMER MODIFY COLUMN FIRST_NAME UNSET MASKING POLICY;
ALTER TABLE IF EXISTS SILVER.DIMCUSTOMER MODIFY COLUMN LAST_NAME UNSET MASKING POLICY;
ALTER TABLE IF EXISTS SILVER.DIMCUSTOMER MODIFY COLUMN EMAIL_ADDRESS UNSET MASKING POLICY;
ALTER TABLE IF EXISTS SILVER.DIMCUSTOMER MODIFY COLUMN CITY UNSET MASKING POLICY;
ALTER TABLE IF EXISTS SILVER.DIMCUSTOMER MODIFY COLUMN STATE_PROVINCE UNSET MASKING POLICY;
-- Gold layer
ALTER TABLE IF EXISTS GOLD.FACTDAILYTRANSACTION MODIFY COLUMN AMOUNT UNSET MASKING POLICY;
ALTER TABLE IF EXISTS GOLD.FACTDAILYAGG MODIFY COLUMN TOTAL_AMOUNT UNSET MASKING POLICY;

-- Masking policies
CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_NAME AS(VAL STRING)
RETURNS STRING ->
CASE
    WHEN IS_ROLE_IN_SESSION('SYSADMIN') OR IS_ROLE_IN_SESSION('ACCOUNTADMIN')
        THEN VAL
    WHEN VAL IS NULL
        THEN NULL
    ELSE LEFT(VAL, 1) || '***'
END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_EMAIL AS(VAL STRING)
RETURNS STRING ->
CASE
    WHEN IS_ROLE_IN_SESSION('SYSADMIN') OR IS_ROLE_IN_SESSION('ACCOUNTADMIN')
        THEN VAL
    WHEN VAL IS NULL
        THEN NULL
    ELSE LEFT(VAL, 1) || '***@' || SPLIT_PART(VAL, '@', 2)
END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_PHONE AS(VAL STRING)
RETURNS STRING ->
CASE
    WHEN IS_ROLE_IN_SESSION('SYSADMIN') OR IS_ROLE_IN_SESSION('ACCOUNTADMIN')
        THEN VAL
    WHEN VAL IS NULL
        THEN NULL
    ELSE '***-***-' || RIGHT(VAL, 4)
END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_LOCATION AS(VAL STRING)
RETURNS STRING ->
CASE
    WHEN IS_ROLE_IN_SESSION('SYSADMIN') OR IS_ROLE_IN_SESSION('ACCOUNTADMIN')
        THEN VAL
    WHEN VAL IS NULL
        THEN NULL
    ELSE LEFT(VAL, 1) || '***'
END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_FINANCIAL_ID AS(VAL STRING)
RETURNS STRING ->
CASE
    WHEN IS_ROLE_IN_SESSION('SYSADMIN') OR IS_ROLE_IN_SESSION('ACCOUNTADMIN')
        THEN VAL
    WHEN VAL IS NULL
        THEN NULL
    ELSE SPLIT_PART(VAL, '-', 1) || '-***'
END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_AMOUNT AS(VAL NUMBER(18, 2))
RETURNS NUMBER(18, 2) ->
CASE
    WHEN IS_ROLE_IN_SESSION('SYSADMIN') OR IS_ROLE_IN_SESSION('ACCOUNTADMIN')
        THEN VAL
    ELSE 0.00
END;

-- Apply policies - Bronze layer
ALTER TABLE BRONZE.T_CUSTOMER MODIFY COLUMN FIRST_NAME SET MASKING POLICY GOVERNANCE.MASK_NAME;
ALTER TABLE BRONZE.T_CUSTOMER MODIFY COLUMN LAST_NAME SET MASKING POLICY GOVERNANCE.MASK_NAME;
ALTER TABLE BRONZE.T_CUSTOMER MODIFY COLUMN EMAIL_ADDRESS SET MASKING POLICY GOVERNANCE.MASK_EMAIL;
ALTER TABLE BRONZE.T_CUSTOMER MODIFY COLUMN PHONE_NUMBER SET MASKING POLICY GOVERNANCE.MASK_PHONE;
ALTER TABLE BRONZE.T_CUSTOMER MODIFY COLUMN CITY SET MASKING POLICY GOVERNANCE.MASK_LOCATION;
ALTER TABLE BRONZE.T_CUSTOMER MODIFY COLUMN STATE_PROVINCE SET MASKING POLICY GOVERNANCE.MASK_LOCATION;

ALTER TABLE BRONZE.T_ACCOUNT MODIFY COLUMN ACCOUNT_ID SET MASKING POLICY GOVERNANCE.MASK_FINANCIAL_ID;
ALTER TABLE BRONZE.T_TRANSACTION MODIFY COLUMN AMOUNT SET MASKING POLICY GOVERNANCE.MASK_AMOUNT;

-- Apply policies - Silver layer
ALTER TABLE SILVER.DIMCUSTOMER MODIFY COLUMN FIRST_NAME SET MASKING POLICY GOVERNANCE.MASK_NAME;
ALTER TABLE SILVER.DIMCUSTOMER MODIFY COLUMN LAST_NAME SET MASKING POLICY GOVERNANCE.MASK_NAME;
ALTER TABLE SILVER.DIMCUSTOMER MODIFY COLUMN EMAIL_ADDRESS SET MASKING POLICY GOVERNANCE.MASK_EMAIL;
ALTER TABLE SILVER.DIMCUSTOMER MODIFY COLUMN CITY SET MASKING POLICY GOVERNANCE.MASK_LOCATION;
ALTER TABLE SILVER.DIMCUSTOMER MODIFY COLUMN STATE_PROVINCE SET MASKING POLICY GOVERNANCE.MASK_LOCATION;

-- Apply policies - Gold layer
ALTER TABLE GOLD.FACTDAILYTRANSACTION MODIFY COLUMN AMOUNT SET MASKING POLICY GOVERNANCE.MASK_AMOUNT;
ALTER TABLE GOLD.FACTDAILYAGG MODIFY COLUMN TOTAL_AMOUNT SET MASKING POLICY GOVERNANCE.MASK_AMOUNT;
