/* ============================================================
   schemachange Migration: V1.1.0__bronze_tables.sql
   PURPOSE : Bronze layer DDL - raw staging tables
   ============================================================ */

USE DATABASE {{ database }};
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE BRONZE.T_CUSTOMER
(
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL_ADDRESS VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    CITY VARCHAR(50),
    STATE_PROVINCE VARCHAR(50),
    COUNTRY VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRONZE.T_ACCOUNT
(
    ACCOUNT_ID VARCHAR(50) NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_TYPE VARCHAR(30),
    STATUS VARCHAR(20),
    CURRENCY_CODE VARCHAR(10),
    OPEN_DATE DATE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRONZE.T_TRANSACTION
(
    TRANSACTION_ID VARCHAR(50) NOT NULL,
    ACCOUNT_ID VARCHAR(50) NOT NULL,
    TRANSACTION_DATE TIMESTAMP_NTZ NOT NULL,
    TRANSACTION_TYPE VARCHAR(30),
    AMOUNT DECIMAL(18, 2),
    DESCRIPTION VARCHAR(255),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
