/* ============================================================
   Domain   : governance
   Layer    : n/a
   Purpose  : Always - Apply grants on every deployment
   Author   : team-governance
   ============================================================ */

USE ROLE SECURITYADMIN;

-- Ecomm grants
GRANT USAGE ON DATABASE {{ database }} TO ROLE RL_ECOMM_READER;
GRANT USAGE ON SCHEMA {{ database }}.BRONZE TO ROLE RL_ECOMM_READER;
GRANT USAGE ON SCHEMA {{ database }}.SILVER TO ROLE RL_ECOMM_READER;
GRANT USAGE ON SCHEMA {{ database }}.GOLD TO ROLE RL_ECOMM_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ database }}.GOLD TO ROLE RL_ECOMM_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA {{ database }}.GOLD TO ROLE RL_ECOMM_READER;

GRANT USAGE ON DATABASE {{ database }} TO ROLE RL_ECOMM_WRITER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ database }} TO ROLE RL_ECOMM_WRITER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {{ database }}.BRONZE TO ROLE RL_ECOMM_WRITER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ database }}.SILVER TO ROLE RL_ECOMM_WRITER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ database }}.GOLD TO ROLE RL_ECOMM_WRITER;

-- Bookings grants
GRANT USAGE ON DATABASE {{ database }} TO ROLE RL_BOOKINGS_READER;
GRANT USAGE ON SCHEMA {{ database }}.GOLD TO ROLE RL_BOOKINGS_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ database }}.GOLD TO ROLE RL_BOOKINGS_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA {{ database }}.GOLD TO ROLE RL_BOOKINGS_READER;

GRANT USAGE ON DATABASE {{ database }} TO ROLE RL_BOOKINGS_WRITER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ database }} TO ROLE RL_BOOKINGS_WRITER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {{ database }}.BRONZE TO ROLE RL_BOOKINGS_WRITER;

-- Aftermarket grants
GRANT USAGE ON DATABASE {{ database }} TO ROLE RL_AFTERMARKET_READER;
GRANT USAGE ON SCHEMA {{ database }}.GOLD TO ROLE RL_AFTERMARKET_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ database }}.GOLD TO ROLE RL_AFTERMARKET_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA {{ database }}.GOLD TO ROLE RL_AFTERMARKET_READER;

GRANT USAGE ON DATABASE {{ database }} TO ROLE RL_AFTERMARKET_WRITER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ database }} TO ROLE RL_AFTERMARKET_WRITER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {{ database }}.BRONZE TO ROLE RL_AFTERMARKET_WRITER;

-- UDS grants
GRANT USAGE ON DATABASE {{ database }} TO ROLE RL_UDS_READER;
GRANT USAGE ON SCHEMA {{ database }}.GOLD TO ROLE RL_UDS_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ database }}.GOLD TO ROLE RL_UDS_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA {{ database }}.GOLD TO ROLE RL_UDS_READER;

GRANT USAGE ON DATABASE {{ database }} TO ROLE RL_UDS_WRITER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ database }} TO ROLE RL_UDS_WRITER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {{ database }}.BRONZE TO ROLE RL_UDS_WRITER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ database }}.SILVER TO ROLE RL_UDS_WRITER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ database }}.GOLD TO ROLE RL_UDS_WRITER;

-- Analytics role - gold layer read across all domains
GRANT USAGE ON DATABASE {{ database }} TO ROLE RL_ANALYTICS;
GRANT USAGE ON SCHEMA {{ database }}.GOLD TO ROLE RL_ANALYTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ database }}.GOLD TO ROLE RL_ANALYTICS;
GRANT SELECT ON ALL VIEWS IN SCHEMA {{ database }}.GOLD TO ROLE RL_ANALYTICS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{ database }}.GOLD TO ROLE RL_ANALYTICS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA {{ database }}.GOLD TO ROLE RL_ANALYTICS;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE {{ warehouse }} TO ROLE RL_ANALYTICS;
GRANT USAGE ON WAREHOUSE {{ warehouse }} TO ROLE RL_ECOMM_READER;
GRANT USAGE ON WAREHOUSE {{ warehouse }} TO ROLE RL_BOOKINGS_READER;
GRANT USAGE ON WAREHOUSE {{ warehouse }} TO ROLE RL_AFTERMARKET_READER;
GRANT USAGE ON WAREHOUSE {{ warehouse }} TO ROLE RL_UDS_READER;
