/* ============================================================
   schemachange Repeatable: R__gold_views.sql
   PURPOSE : Gold layer views - recreated whenever this file changes
   ============================================================ */

USE DATABASE {{ database }};
USE SCHEMA GOLD;

CREATE OR REPLACE VIEW GOLD.MONTHLYSPENDPROFILE AS
SELECT
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.CITY,
    C.STATE_PROVINCE,
    F.TRANSACTION_TYPE,
    DATE_TRUNC('MONTH', F.DATE_KEY) AS MONTH_KEY,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(F.AMOUNT) AS TOTAL_SPEND,
    AVG(F.AMOUNT) AS AVG_TRANSACTION,
    MIN(F.AMOUNT) AS MIN_TRANSACTION,
    MAX(F.AMOUNT) AS MAX_TRANSACTION
FROM GOLD.FACTDAILYTRANSACTION AS F
INNER JOIN SILVER.DIMCUSTOMER AS C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
    AND C.CURRENT_FLAG = 'Y'
GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.CITY,
    C.STATE_PROVINCE,
    DATE_TRUNC('MONTH', F.DATE_KEY),
    F.TRANSACTION_TYPE;

CREATE OR REPLACE VIEW GOLD.TXNTYPETREND AS
SELECT
    F.TRANSACTION_TYPE,
    DATE_TRUNC('MONTH', F.DATE_KEY) AS MONTH_KEY,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(F.AMOUNT) AS TOTAL_AMOUNT,
    AVG(F.AMOUNT) AS AVG_AMOUNT,
    COUNT(DISTINCT F.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    COUNT(DISTINCT F.ACCOUNT_ID) AS UNIQUE_ACCOUNTS,
    SUM(F.AMOUNT) / NULLIF(COUNT(DISTINCT F.CUSTOMER_ID), 0) AS AVG_SPEND_PER_CUSTOMER
FROM GOLD.FACTDAILYTRANSACTION AS F
GROUP BY
    DATE_TRUNC('MONTH', F.DATE_KEY),
    F.TRANSACTION_TYPE;
